version: '3.2'

services:
  server:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ".:/code"
    depends_on:
      - mongo       
  mongo:
    image: mongo:4.2
    volumes:
      - 'mongo:/data/db'
    ports:
      - '27017:27017'

volumes:
  mongo: ~