# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: 
      - chore/*


jobs:
  lint:
    env:
      COMPOSE_FILE: "docker-compose.yml:docker-compose.gitlab-ci.yml"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
     - name: Lint
       run: |
          cp -f .env.dist .env
          docker login -u github-ci-token -p $GITHUB_TOKEN docker.pkg.github.com
          docker-compose pull server || true
          make start
          make lint
  test:
    env:
      COMPOSE_FILE: "docker-compose.yml:docker-compose.gitlab-ci.yml"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
     - name: Test
       run: |
          cp -f .env.dist .env
          docker login -u github-ci-token -p $GITHUB_TOKEN docker.pkg.github.com
          docker-compose pull server || true
          make start
          make test
          
